echo Groupname >> runs.txt
./buildpipeline.sh delay 10
./buildpipeline.sh delay 10
./buildpipeline.sh delay 10
./buildpipeline.sh delay 10
./buildpipeline.sh delay 20
./buildpipeline.sh delay 20
./buildpipeline.sh delay 20
./buildpipeline.sh delay 20
./buildpipeline.sh delay 50
./buildpipeline.sh delay 50
./buildpipeline.sh delay 50
./buildpipeline.sh delay 50
./buildpipeline.sh delay 100
./buildpipeline.sh delay 100
./buildpipeline.sh delay 100
./buildpipeline.sh delay 100
./buildpipeline.sh delay 200
./buildpipeline.sh delay 200
./buildpipeline.sh delay 200
./buildpipeline.sh delay 200